#pragma once
#include "pch.hpp"

namespace Ethereal {
    enum class ETHEREAL_PIXEL_FORMAT : uint8_t
    {
        ETHEREAL_PIXEL_FORMAT_UNKNOWN = 0,
        ETHEREAL_PIXEL_FORMAT_R8G8B8_UNORM,
        ETHEREAL_PIXEL_FORMAT_R8G8B8_SRGB,
        ETHEREAL_PIXEL_FORMAT_R8G8B8A8_UNORM,
        ETHEREAL_PIXEL_FORMAT_R8G8B8A8_SRGB,
        ETHEREAL_PIXEL_FORMAT_R32G32_FLOAT,
        ETHEREAL_PIXEL_FORMAT_R32G32B32_FLOAT,
        ETHEREAL_PIXEL_FORMAT_R32G32B32A32_FLOAT
    };

    enum class ETHEREAL_IMAGE_TYPE : uint8_t
    {
        ETHEREAL_IMAGE_TYPE_UNKNOWM = 0,
        ETHEREAL_IMAGE_TYPE_2D
    };
}