#pragma once

#define ET_ENABLE_PROFILING 1

#if ET_ENABLE_PROFILING
#include "optick/optick.h"
#endif

#if ET_ENABLE_PROFILING
#define ET_PROFILE_FRAME(...) OPTICK_FRAME(__VA_ARGS__)
#define ET_PROFILE_FUNC(...) OPTICK_EVENT(__VA_ARGS__)
#define ET_PROFILE_TAG(NAME, ...) OPTICK_TAG(NAME, __VA_ARGS__)
#define ET_PROFILE_SCOPE_DYNAMIC(NAME) OPTICK_EVENT_DYNAMIC(NAME)
#define ET_PROFILE_THREAD(...) OPTICK_THREAD(__VA_ARGS__)
#define ET_PROFILE_GPU_EVENT(...) OPTICK_GPU_EVENT(__VA_ARGS__)
#define ET_PROFILE_GPU_CONTEXT(...) OPTICK_GPU_CONTEXT(__VA_ARGS__)
#define ET_PROFILE_GPU_INIT_VULKAN(DEVICES, PHYSICAL_DEVICES, CMD_QUEUES, CMD_QUEUES_FAMILY, \
                                   NUM_CMD_QUEUS, FUNCTIONS)                                 \
    OPTICK_GPU_INIT_VULKAN(DEVICES, PHYSICAL_DEVICES, CMD_QUEUES, CMD_QUEUES_FAMILY,         \
                           NUM_CMD_QUEUS, FUNCTIONS)
#else
#define ET_PROFILE_FRAME(...)
#define ET_PROFILE_FUNC(...)
#define ET_PROFILE_TAG(NAME, ...)
#define ET_PROFILE_SCOPE_DYNAMIC(NAME)
#define ET_PROFILE_THREAD(...)
#define ET_PROFILE_GPU_EVENT(...) 
#define ET_PROFILE_GPU_CONTEXT(...)
#define ET_PROFILE_GPU_INIT_VULKAN(...)
#endif
