#pragma once
#include "Base/Meta/Serializer.h"
#include "Base/Meta/_generated/serializer/Quaternion.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Vector.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Material.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Matrix.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Ref.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Transform.serializer.gen.h"
#include "Base/Meta/_generated/serializer/UUID.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Asset.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Animation.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Mesh.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Camera.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Components.serializer.gen.h"
#include "Base/Meta/_generated/serializer/Scene.serializer.gen.h"

